[package]
name = "soulbound-token"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "22.0.7", features = ["testutils"] }
wee_alloc = "0.4.5"
